# Site settings
title: garaetteok95
description: garaetteok95 Github Blog
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://garaetteok95.github.io"

# User settings
username: garaetteok95
user_description: I'm Embedded Developer :)
user_title: Embedded Developer
email: garaetteok95@gmail.com
github_username: garaetteok95


exclude: ['package.json', 'src' , 'node_modules']
